name: Precheck before Merging PRs

on:
  pull_request:
    branches:
      - dev
      - stg
      - prod

jobs:
  installation:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Eslint check
        run: npx eslint . --fix

      - name: Prettify
        run: npx prettier . --write

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
